name: xor
version: 0.1.1
author: Jeremi Gendron <gendronjeremi@gmail.com>
homepage: https://github.com/jeremigendron
repository: https://github.com/jeremigendron/xor
description: xor Uint8List`s together

environment:
  sdk: ">=2.1.0-1 <3.0.0" 

dev_dependencies:
  test: ^1.5.0
  hex: ^0.1.2

